### ISSUE TITLE
Using rlig features to replace Latin text

### ISSUE THREAD

**Issue by jackhumbert** [lakmeer/zbalermorna#3]
I'm not sure if this is the best way to phrase this solution, but it looks like it's possible to stick this block at the beginning of the `zlm.feature.ls` output script to allow all of the awesome ligature stuff to work on normal latin text (I may be missing some conversions here):

```livescript
  section "Latin Mapping", ->
    feature "C", ->
      for c in CONSN
        log "  sub #c by ZLM_#c;"
        log "  sub #{ c.toLowerCase() } by ZLM_#c;"
      log "  sub period by ZLM_NULL;"
      log "  sub quotesingle by ZLM_H;"
    feature "V", ->
      for v in VOWELS
        log "  sub #v by ZLM_FULL_#v;"
        log "  sub #{ v.toLowerCase() } by ZLM_DIACRITIC_#v;"
      log "  sub w by ZLM_SEMIVOWEL_W;"
      log "  sub W by ZLM_SEMIVOWEL_W;"
      log "  sub q by ZLM_SEMIVOWEL_Q;"
      log "  sub Q by ZLM_SEMIVOWEL_Q;"
    feature "VV", ->
      log "  sub ZLM_FULL_A ZLM_FULL_I by ZLM_FULL_AI;"
      log "  sub ZLM_FULL_O ZLM_FULL_I by ZLM_FULL_OI;"
      log "  sub ZLM_FULL_E ZLM_FULL_I by ZLM_FULL_EI;"
      log "  sub ZLM_FULL_A ZLM_FULL_U by ZLM_FULL_AU;"
```

Is this desirable? I can see wanting to separate latin and zlm stuff so they can be used together in the same text block without having to switch fonts, but I think we could use something besides `rlig` to allow easy disabling of the latin subbing - there's quite a few opentype features that could be used, but I'm not sure which would work the best yet.

The one caveat I found is that all of the glyphs you're subbing need to be defined in the initial font, so I have a bunch of blank glyphs with 0 width in mine (merging the feature will error out otherwise). Ideally these glyphs would retain their latin versions, which is easy for a converted font, but kind of a pain for new zlm fonts. Maybe that's just an optional feature of the base font, though.

This is what my textarea looks like on my test page (working on another font too!) :)

![image](https://user-images.githubusercontent.com/141431/62215373-d43f3080-b374-11e9-9c55-f82830c05d2a.png)

**Comment by jackhumbert** [comment]
As an example, we could define the latin-replacing feature as `ss01`, which is disabled by default in my browser, but can be controlled very easily with something like this:

```css
textarea {
  font-feature-settings: "ss01" 1;
}
```

**Comment by jackhumbert** [comment]
Additionally we could enable number substitution in a separate table like `ss02`:

```livescript
    feature-custom "Numbers", "ss02", ->
      log "  sub zero by ZLM_NO;"
      log "  sub one by ZLM_PA;"
      log "  sub two by ZLM_RE;"
      log "  sub three by ZLM_CI;"
      log "  sub four by ZLM_VO;"
      log "  sub five by ZLM_MU;"
      log "  sub six by ZLM_XA;"
      log "  sub seven by ZLM_ZE;"
      log "  sub eight by ZLM_BI;"
      log "  sub nine by ZLM_SO;"
```

And both could be enabled with:

```css
.latin-sub {
  font-feature-settings: "ss01" 1, "ss02" 1;
}
```

Separating features into separate tables seems like a good way to introduce some flexibility into the fonts, and allows people to render the text how they choose.

**Comment by lagleki** [comment]
Is ".ai" covered by the proposal?

**Comment by jackhumbert** [comment]
@lagleki It looks like it :) you'll have to believe me when I say I typed `.ai` until I get my repo updated haha.

![image](https://user-images.githubusercontent.com/141431/62219481-68f95c80-b37c-11e9-894a-203a64cc1ac2.png)

**Comment by jackhumbert** [comment]
I've got a demo of this up with two new fonts: https://jackhumbert.github.io/zbalermorna/test/index.html - one of them is the open sourced Lato, which is merged with the modifications I made for zlm.

If you can think of any other tests/combinations that need to be checked, I can add them to that page.

I can clean this up for a pull request - let me know if you see anything that needs changed with it!

**Comment by lagleki** [comment]
On Thu, Aug 1, 2019, 07:37 Jack Humbert <notifications@github.com> wrote:

> I've got a demo of this up with two new fonts:
> https://jackhumbert.github.io/zbalermorna/test/index.html - one of them
> is the open sourced Lato, which is merged with the modifications I made for
> zlm.
>
> If you can think of any other tests/combinations that need to be checked,
> I can add them to that page.
>

plukau
.au

**Comment by jackhumbert** [comment]
@lagleki great! I got those added. You should be able to type them out in the textarea on the test page, but here's what they look like for me:

![image](https://user-images.githubusercontent.com/141431/62294093-3745cb80-b438-11e9-9312-ddb5f033a699.png)

I'm experimenting with stylistic alternatives for zlm characters, and it looks like we can define our own tables - on the test page, those alts use the `zlm2` table. I'm not sure how widely supported being able to turn on/off arbitrary tables like this is (I know sublime text is limited in what tables it supports), but it could be useful, and we could come up with some standards for zlm options.

**Comment by lakmeer** [comment]
Hi Jack, sorry for the late reply, I have not had access to a computer the past day.
You will find some of this response disappointing, my apologies :sweat_smile:

### Allowing liga to work on latin glyphs
This is in fact _NOT_ desirable. Sorry about that, seeing as you already put in a bunch of work.
It is convenient, and in fact this is how my very old lojban fonts used to work, including la srilermorna and the early versions of ZLM. However, this approach is naive and it is, uh, like "bad citizenship" to construct fonts this way. It is naldrani and they do not play nice with other fonts. The codepoint for the latin letter C _means_ "a glyph depicting the latin letter C" and `ZLM_C` is not one of those, nor is the ligature ZLM_CA and so on.
The correct way is to give the new glyphs thier own codepoints in unused unicode space and develop an input system that is appropriate for accessing them. This is what this repo is about (although it is unloved; I appreciate you taking an interest :smiley:). A working input system would actually use the same keystrokes, but have proper codepoints and play nice with existing latin text, allow the development of typefaces for ZLM which work correctly with multilingual font rendering systems, and sit alongside other combining othographies like Korean, Mongolian or Devanagari in the way that they behave with real-world languages. Apart from being the most correct way of doing it, I also feel this helps to elevate Lojban and ZLM to a peer-like status with other languages.

### Numeric auto-conversion
I also tried this in a previous incarnation :) It's neat but same rationale as above applies. `DIGIT_ONE` is not `ZLM_PA`, nor should `ZLM_PA` be considered Numeric (see [character properties](https://en.wikipedia.org/wiki/Unicode_character_property#Numeric_values_and_types))

### Advanced Opentype features
Many common font renderers do not support even a minority of Opentype features, unfortunately. There are many amazing and useful features in the spec that are very poorly supported on everyday systems :sweat_smile:. Even some very simple ligating or replacement features are sparsely supported, which was frustrating because many things about ZLM _should_ be easier, but I ended up settling on a lowest-common-denominator subset of features to target the greatest range of renderers. I can't remember which ones I discarded since it's been several years.

### Dynamic table switching
It's fine to do this for testing purposes on the javascript IME emulator, but in general, switching tables on and off is also not desirable. The system should be as 'dumb' (ie: simple and predicatable) as possible. This also means working like other non-latin input methods and not requiring a custom interface. Imagine using this in MS Word. How are these controls made available? Perhaps there is a way I'm not aware of, but consider, for example, a non-technical Japanese user (hiragana is a comparable level of complexity as ZLM, and has some similar principles). They would be accustomed to using their computer with the Japanese IME - how would this user expect a Lojbanic IME to behave? It should behave in the least surprising way possible.

### Stylistic alts
This is a really cool idea, especially for more handwriting-y typefaces. I've not used a typeface that does this before, I know some will auto-sub alts for you in context (eg, to prevent two 'e's from looking identical next to each other), but I'm pretty sure that sophisticated fonts (think like, wedding invitations with big scrawly letters) use thier IME to provide an interface for this. Might pay to research some existing examples to see how it's commonly acheived.

### Glyph Design
Be careful when heavily basing a ZLM typeface on an existing Latin typeface. Design decisions which have been made to optimise latin glyphs do not necessarily apply to ZLM, eg the stroke direction and the proportions are usually not compatible. In particular, notice how the ascenders are much shorter than the 1/4 recommended for ZLM. Apart from not leaving as much room for nice big vowels (critical at small font sizes, remember to test for this), it also gives a Latin flavour that is very recognisable; it looks more like 'weird latin' than a distinct language.
That said, the Lato-based one looks quite handsome, I rather like it; however I think we 'get away' with that one because Lato is quite humanist and the glyphs have very uniform stroke weights. The Times-based one doesn't work very well in my opinion. I have also tried that before :P

This turned out quite long, again sorry for the delayed reply, an earlier one might have saved you some time. Overall I very much appreciate your interest in this project and please dont take this critique as discouragement :)

mu'o

**Comment by lagleki** [comment]
I'm neutral in this discussion. I can transpile existing texts using https://framagit.org/peppercarrot/tools/blob/zbalermorna/utils/zbalermorna/piper.js just fine but with ligatures it's much easier to type. You basically need to install and enable a font and that's it. With IME one needs trickier software.

**Comment by jackhumbert** [comment]
No worries! It's really just that one feature section :) I think having the discrete Unicode space for zlm is awesome, and that makes a lot of sense, especially with how the fonts are organized - the Lato and zlm-converted stuff can live together in the same font like many of the other scripts in there. It's possible to trigger a substitution table with a certain language/script via a lookup table, and [I know Lojban is listed as a valid language in OpenType](https://docs.microsoft.com/en-us/typography/opentype/spec/languagetags) - maybe we could push for a script tag for Zbalermorna (`Script tags correspond to the contiguous character code ranges in Unicode.` - from the ISO doc for OpenType)? Until then, maybe we could borrow a script tag? I realize this might be considered blasphemy :)

I think having the option to easily type/convert Lojban to zlm would be a nice feature to have while support for a dedicated input method* is in the works. One advantage to having the latin-subbing tables enabled is that a lot of work that's been done for Lojban automatically works with the zlm script (spell-checking, dictionary look-up), along with copy & paste still working with other fonts. I suppose a smart enough IME could handle all of these things as well. (edit: I got copy & paste working in the IME!)

I realize that what I'm using to develop/preview things probably isn't very widely supported, but I am curious what workarounds would be possible - in the case where limited features are supported, I think it's usually just a limited number of tables (~~e.g. Sublime Text 3 supports `clig`, `liga`, and `calt`~~ they limit the ligatures to various symbol characters at this time), which is something we have control over with the fonts :) I haven't done any research on it yet, but I'm curious what limitations things like Word have. For Google Docs, I believe we'd be able to construct a font and submit it to [Google Fonts](https://github.com/google/fonts) and have it show up as an option, which could go a long way. I would imagine we could petition other open source fonts to add the zlm block that we or the creators put together.

For stylistic alts, would we want to have any standard in the Unicode spec, or just let people place things wherever they want as long as it's outside of the defined zlm one (and others)?

I have to admit, with some of these fonts, I was definitely going for a "weird latin" look :) I think this is where the stylistic alts can really come into play - having options to make the appearance more distinctly Zbalermornic, or strictly following the existing font's rules for their latin glyphs would be a neat feature. I have a bunch of alternate glyphs saved from when I was experimenting with which worked the best - exposing them via the `salt` or `ss*` tables might work well. Here's some of them:

![image](https://user-images.githubusercontent.com/141431/62308409-47b76f80-b453-11e9-940b-a91902ae9ecf.png)

\*This is what the ibus stuff refers to, right? I'm not super familiar with it, and have been using Windows machines for the past couple years, but I'd be interested in working on something like this!

All this being said, I know I don't have much of a leg in the direction of Zbalermorna - I just enjoy creating the fonts and making them look good :)

**Comment by lagleki** [comment]
These are all the fonts used at least once in the localisation of pepper and carrot. So kinda possible goal for zlm

https://framagit.org/peppercarrot/fonts/tree/master/Latin

**Comment by jackhumbert** [comment]
@lagleki nice! I started working on Pepper Carrot and Lavi (both are on the [test page](https://jackhumbert.github.io/zbalermorna/test/index.html#pepper-carrot-zlm)) since you linked those two earlier :)

**Comment by jackhumbert** [comment]
I think this can be closed - I'll move the other discussions elsewhere :)
